import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic";
import Script from 'next/script'
import {useState} from "react";
import CityInfoCard from "../components/city_info_card";
// @ts-ignore
const InsuranceMap = dynamic(() => import('../components/insurance_map'), {ssr: false})
// @ts-ignore
const FilterInsurance = dynamic(() => import('../components/filter_insurance'), {ssr: false})

const inter = Inter({subsets: ['latin']})

export default function Home() {
  const [view, setView] = useState('map');
  const [selected, setSelected] = useState(null);

  return (
    <>
      <Head>
        <title>AIO</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/logo.svg"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="preconnect" href="https://fonts.googleapis.com/"/>
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin=""/>
        <link href="/current_web/css2" rel="stylesheet"/>
        <link rel="stylesheet" href="/current_web/all.min.css"/>
        <link href="/current_web/bootstrap.min.css" rel="stylesheet"/>
        <link rel="stylesheet" href="/current_web/owl.carousel.min.css"/>
        <link rel="stylesheet" href="/current_web/owl.theme.default.min.css"/>
        <link rel="stylesheet" href="/current_web/style.css"/>
        <link rel="stylesheet" href="/current_web/responsive.css"/>
        <title>AIO</title>
        <link rel="icon" type="image/png" href="https://baohanh.viettelaio.vn/assets/img/fav.png"/>
      </Head>
      <body className="fixed-header">
      <div className="wrapper">
        <header className="header">
          <div className="container">
            <div className="inner-header d-flex justify-content-between align-items-center">
              <div className="logo">
                <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/logo.svg" alt=""/></a>
              </div>
              <div className="wrap-menu">
                            <span className="close">
                                <i className="fal fa-times"></i>
                            </span>
                <div className="primary-menu">
                  <ul className="d-flex align-items-center">
                    <li><a href="https://baohanh.viettelaio.vn/#block-about" className="active-menu">Giới thiệu</a></li>
                    <li><a href="https://baohanh.viettelaio.vn/#block-policy" className="">Chính sách bảo hành</a></li>
                    <li><a href="https://baohanh.viettelaio.vn/#block-warranty" className="">Trung tâm bảo hành</a></li>
                    <li><a href="https://baohanh.viettelaio.vn/#block-app" className="">App Lifecare</a></li>
                    <li><a href="https://baohanh.viettelaio.vn/#block-supports" className="">Hỗ trợ</a></li>
                  </ul>
                </div>
              </div>
              <div className="menu-toggle">
                <i className="fal fa-bars"></i>
              </div>
            </div>
          </div>
        </header>
        <main className="main-page">
          <section className="block-session" id="block-about">
            <div className="container">
              <div className="wrap-content-about">
                <h1 className="title-h1">Giới thiệu</h1>
                <div className="description">
                  <p>Tổng Công ty Cổ phần Công trình Viettel được thành lập năm 1995, trực thuộc Tập đoàn Công Nghiệp -
                    Viễn thông Quân đội, cung cấp dịch vụ trên nền tảng kỹ thuật hàng đầu Việt Nam cho khách hàng doanh
                    nghiệp và hơn 27 triệu hộ gia đình tại Việt Nam.</p>
                  <p>Kế thừa sứ mệnh “Dựng xây cuộc sống mới” từ Viettel Construction, năm 2022, Viettel Construction ra
                    mắt thương hiệu AIO trở thành đơn vị chuyên sản xuất và phân phối các thiết bị điện gia đình và các
                    giải pháp sống thông minh toàn diện, tiên tiến và hiện đại nhất.</p>
                </div>
              </div>
            </div>
          </section>
          <section className="block-session" id="block-products">
            <div className="container">
              <div className="header-block">
                <h3 className="title-h3">Sản phẩm nổi bật</h3>
                <p className="subtitle">Danh sách sản phẩm nổi bật được nhiều người dùng sử dụng của Viettel AIO</p>
              </div>
              <div className="list-products owl-carousel owl-theme owl-loaded owl-drag">


                <div className="owl-stage-outer">
                  <div className="owl-stage"
                       style={{transition: "all 0s ease 0s", width: 3618, transform: "translate3d(-804px, 0px, 0px)"}}>
                    <div className="owl-item cloned" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p1.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Bếp từ đôi AIO</a>
                      </div>
                    </div>
                    <div className="owl-item cloned" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p2.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Quạt sưởi gốm AIO</a>
                      </div>
                    </div>
                    <div className="owl-item cloned active" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p3.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Nồi lẩu điện AIO</a>
                      </div>
                    </div>
                    <div className="owl-item active center" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p1.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Bếp từ đôi AIO</a>
                      </div>
                    </div>
                    <div className="owl-item active" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p2.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Quạt sưởi gốm AIO</a>
                      </div>
                    </div>
                    <div className="owl-item" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p3.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Nồi lẩu điện AIO</a>
                      </div>
                    </div>
                    <div className="owl-item cloned" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p1.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Bếp từ đôi AIO</a>
                      </div>
                    </div>
                    <div className="owl-item cloned" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p2.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Quạt sưởi gốm AIO</a>
                      </div>
                    </div>
                    <div className="owl-item cloned" style={{width: 372, marginRight: 30}}>
                      <div className="item">
                        <div className="icon">
                          <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/p3.png" alt=""/></a>
                        </div>
                        <a href="https://baohanh.viettelaio.vn/#">Nồi lẩu điện AIO</a>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="owl-nav disabled">
                  <button type="button" role="presentation" className="owl-prev"><span aria-label="Previous">‹</span>
                  </button>
                  <button type="button" role="presentation" className="owl-next"><span aria-label="Next">›</span>
                  </button>
                </div>
                <div className="owl-dots disabled">
                  <button role="button" className="owl-dot active"><span></span></button>
                  <button role="button" className="owl-dot"><span></span></button>
                  <button role="button" className="owl-dot"><span></span></button>
                </div>
              </div>
            </div>
          </section>
          <section className="block-session" id="block-policy">
            <div className="header-block">
              <h3 className="title-h3">Chính sách bảo hành</h3>
            </div>
            <div className="lists">
              <div className="item">
                <div className="container">
                  <div className="images">
                    <img src="/current_web/m1.png" alt=""/>
                  </div>
                  <div className="content-item">
                    <ol>
                      <ul>
                        <li>Để liên hệ bảo hành quý khách hàng vui lòng liên hệ Hotline: 1900 98 98 68 hoặc gửi mail:
                          cskhcongtrinhviettel@viettel.com.vn.
                        </li>
                        <li>Trong vòng 7 ngày kể từ khi hàng hóa được kích hoạt nếu hàng hóa bị lỗi sản xuất chúng tôi
                          sẽ tiến hành 1 đổi 1.
                        </li>
                        <li>Sản phẩm được bảo hành sửa chữa miễn phí trong vòng 24 tháng (Lỗi do nhà sản xuất).</li>
                        <li>Trong thời gian bảo hành, chúng tôi vẫn tiếp nhận hàng hóa ngay cả khi do lỗi từ khách hàng.
                          Mọi chi phí liên quan tới việc sửa chữa Hàng hóa, thay thế, vận chuyển Hàng hóa sẽ do khách
                          hàng chịu.
                        </li>
                        <li>Trong thời hạn bảo hành, nếu quá thời hạn 10 ngày quy định mà chúng tôi vẫn chưa hoàn thành
                          nghĩa vụ bảo hành thì khách hàng có quyền thuê một bên thứ ba để thực hiện việc sửa chữa, thay
                          thế Hàng hóa. Chúng tôi chịu mọi chi phí thực tế phát sinh liên quan đến việc sửa chữa và/hoặc
                          thay thế Hàng hóa.
                        </li>
                      </ul>
                    </ol>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="block-session" id="block-warranty">
            <div className="container">
              <div className="header-block">
                <h3 className="title-h3">Trung tâm bảo hành</h3>
                <p className="subtitle">Hiện nay, trung tâm bảo hành của Viettel AIO đã đã bao phủ toàn quốc tại 63 tỉnh
                  thành</p>
              </div>
              <main className={styles.main}>
                <FilterInsurance
                  setView={setView}
                  view={view}
                  selected={selected}
                  setSelected={setSelected}
                />
                {view === 'map' ? <InsuranceMap
                  selected={selected}
                  setSelected={setSelected}
                /> : <div className="list-warranty">
                  <div className="item-warranty">
                    <span className="bg_top">Miền Bắc</span>
                    <div className="table-responsive">
                      <table className="table align-middle table-striped table-hover">
                        <thead>
                        <tr>
                          <th scope="col" className="area">Khu vực</th>
                          <th scope="col" className="no">STT</th>
                          <th scope="col" className="city">Tỉnh/Thành phố</th>
                          <th scope="col" className="address">Địa chỉ</th>
                          <th scope="col" className="phone">Số điện thoại</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                          <th rowSpan={6} className="area">Tây Bắc Bộ</th>
                          <td className="no">1</td>
                          <td className="city">HÒA BÌNH</td>
                          <td className="address">Tòa nhà Viettel, Xóm 8, xã Sủ Ngòi, TP. Hòa Bình, tỉnh Hòa Bình</td>
                          <td className="phone"><a href="tel:0326637777">0326 637 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">2</td>
                          <td className="city">Sơn La</td>
                          <td className="address">Số 1 Chu Văn Thịnh, tổ 01, P. Tô Hiệu, TP. Sơn La, tỉnh Sơn La</td>
                          <td className="phone"><a href="tel:00983122366">0983 122 366</a></td>
                        </tr>
                        <tr>
                          <td className="no">3</td>
                          <td className="city">Điện Biên</td>
                          <td className="address">Số 176 Trường Chinh, tổ 9, P. Tân Thanh, TP. Điện Biên Phủ, tỉnh Điện
                            Biên
                          </td>
                          <td className="city"><a href="tel:0326 897 777">0326 897 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">4</td>
                          <td className="city">Lai Châu</td>
                          <td className="address">Tân Phong, TP Lai Châu, Lai Châu</td>
                          <td className="city"><a href="tel:0326897777">0328517777</a></td>
                        </tr>
                        <tr>
                          <td className="no">5</td>
                          <td className="city">Lào Cai</td>
                          <td className="address">B6 Trần Hưng Đạo, Bắc Lệnh, TP Lào Cai, Lào Cai</td>
                          <td className="city"><a href="tel:0326897777">02146250000</a></td>
                        </tr>
                        <tr>
                          <td className="no">6</td>
                          <td className="city">Yên Bái</td>
                          <td className="address">Tổ dân phố Hồng Phú, Hồng Hà, TP Yên Bái, Yên Bái</td>
                          <td className="city"><a href="tel:0326897777">0326827777</a></td>
                        </tr>
                        <tr>
                          <th rowSpan={9} className="area">Đông Bắc Bộ</th>
                          <td className="no">7</td>
                          <td className="city">Phú Thọ</td>
                          <td className="address">1688 Hùng Vương, P. Nông Trang, TP. Việt Trì, tỉnh Phú Thọ</td>
                          <td className="city"><a href="tel:0326897777">0326 897 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">8</td>
                          <td className="city">Hà Giang</td>
                          <td className="address">218 B Nguyễn Trãi, TP Hà Giang, Hà Giang</td>
                          <td className="city"><a href="tel:02196556888">02196556888</a></td>
                        </tr>
                        <tr>
                          <td className="no">9</td>
                          <td className="city">Tuyên Quang</td>
                          <td className="address">Tổ 9 Tân Quang, TP Tuyên Quang, Tuyên Quang</td>
                          <td className="city"><a href="tel:0326 747 777">0326 747 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">10</td>
                          <td className="city">Cao Bằng</td>
                          <td className="address">Lô 10, Khu Đô Thị Mới,Phường Đề Thám, TP Cao Bằng, Cao Bằng</td>
                          <td className="city"><a href="tel:02066250000">02066250000</a></td>
                        </tr>
                        <tr>
                          <td className="no">11</td>
                          <td className="city">Bắc Kạn</td>
                          <td className="address">Số 46, tổ 10, thành phố Bắc Kạn, tỉnh Bắc Kạn</td>
                          <td className="city"><a href="tel:02096250000">02096250000</a></td>
                        </tr>
                        <tr>
                          <td className="no">12</td>
                          <td className="city">Thái Nguyên</td>
                          <td className="address">Số 4 Hoàng Văn Thụ, TP Thái Nguyên, Thái Nguyên</td>
                          <td className="city"><a href="tel:0326 867 777">0326 867 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">13</td>
                          <td className="city">Lạng Sơn</td>
                          <td className="address">Hùng Vương, Xã Mai Pha, Lạng Sơn</td>
                          <td className="city"><a href="tel:0328497777">0328497777</a></td>
                        </tr>
                        <tr>
                          <td className="no">14</td>
                          <td className="city">Bắc Giang</td>
                          <td className="address">Số 4A, Hoàng Văn Thụ, p Xương Giang, TP Bắc Giang, Bắc Giang</td>
                          <td className="city"><a href="tel:0326907777">0326907777</a></td>
                        </tr>
                        <tr>
                          <td className="no">15</td>
                          <td className="city">Quảng Ninh</td>
                          <td className="address">Tầng 3, Tòa nhà Viettel Quảng Ninh, Số 70 đường Nguyễn Văn Cừ, P.Hồng
                            Hải, TP Hạ Long, Quảng Ninh
                          </td>
                          <td className="city"><a href="tel:0326807777">0326807777</a></td>
                        </tr>
                        <tr>
                          <th rowSpan={10} className="area">Đồng bằng sông Hồng</th>
                          <td className="no">16</td>
                          <td className="city">Bắc Ninh</td>
                          <td className="address">Phố Vũ, Đại Phúc, TP Bắc Ninh, Bắc Ninh</td>
                          <td className="city"><a href="tel:0326597777">0326597777</a></td>
                        </tr>
                        <tr>
                          <td className="no">17</td>
                          <td className="city">Hà Nam</td>
                          <td className="address">Lê Hoàn, Hai Bà Trưng, TP Phủ Lý, Hà Nam</td>
                          <td className="city"><a href="tel:0326617777">0326617777</a></td>
                        </tr>
                        <tr>
                          <td className="no">18</td>
                          <td className="city">Hải Dương</td>
                          <td className="address">169 Bạch Đằng, Trần Phú, TP Hải Dương, Hải Dương</td>
                          <td className="city"><a href="tel:02206250000">02206250000</a></td>
                        </tr>
                        <tr>
                          <td className="no">19</td>
                          <td className="city">Hưng Yên</td>
                          <td className="address">537 Nguyễn Văn Linh, Hiến Nam, TP Hưng Yên, Hưng Yên</td>
                          <td className="city"><a href="tel:0989400032">0989400032</a></td>
                        </tr>
                        <tr>
                          <td className="no">20</td>
                          <td className="city">Nam Định</td>
                          <td className="address">Số 2 Đông A, KĐT Hòa Vượng, Lộc Vượng, TP Nam Định, Nam Định/td&gt;
                          </td>
                          <td className="city"><a href="tel:0326717777">0326717777</a></td>
                        </tr>
                        <tr>
                          <td className="no">21</td>
                          <td className="city">Thái Bình</td>
                          <td className="address">431 Trần Hưng Đạo, Trần Hưng Đạo, TP. Thái Bình, Thái Bình</td>
                          <td className="city"><a href="tel:0326727777">0326727777</a></td>
                        </tr>
                        <tr>
                          <td className="no">22</td>
                          <td className="city">Vĩnh Phúc</td>
                          <td className="address">Khu đô thị Hà Tiên, Định Trung, Vĩnh Yên, Vĩnh Phúc</td>
                          <td className="city"><a href="tel:0989400027">0989400027</a></td>
                        </tr>
                        <tr>
                          <td className="no">23</td>
                          <td className="city">Ninh Bình</td>
                          <td className="address">18 Trần Hưng Đạo, Tân Thành, TP Ninh Bình, Ninh Bình</td>
                          <td className="city"><a href="tel:0989400037">0989 400 037</a></td>
                        </tr>
                        <tr>
                          <td className="no">24</td>
                          <td className="city">Hà Nội</td>
                          <td className="address">Tầng 5, Tháp B, Tòa nhà Central Point, Số 219 Trung Kính, Phường Yên
                            Hoà, Quận Cầu Giấy, Thành phố Hà Nội
                          </td>
                          <td className="city"><a href="tel:0326627777">0326 627 777</a></td>
                        </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div className="item-warranty">
                    <span className="bg_top">Miền Trung</span>
                    <div className="table-responsive">
                      <table className="table align-middle table-striped table-hover">
                        <thead>
                        <tr>
                          <th scope="col" className="area">Khu vực</th>
                          <th scope="col" className="no">STT</th>
                          <th scope="col" className="city">Tỉnh/Thành phố</th>
                          <th scope="col" className="address">Địa chỉ</th>
                          <th scope="col" className="phone">Số điện thoại</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                          <th rowSpan={6} className="area">Bắc Trung Bộ</th>
                          <td className="no">1</td>
                          <td className="city">Thanh Hoá</td>
                          <td className="address">Nam Đại Lộ Lê Lợi, Đông Hương, TP Thanh Hoá, Thanh Hoá</td>
                          <td className="phone"><a href="tel:0326647777">0326647777</a></td>
                        </tr>
                        <tr>
                          <td className="no">2</td>
                          <td className="city">Nghệ An</td>
                          <td className="address">Đại lộ Lê Nin, Hà Huy Tập, TP Vinh, Nghệ An</td>
                          <td className="phone"><a href="tel:0326657777">0326657777</a></td>
                        </tr>
                        <tr>
                          <td className="no">3</td>
                          <td className="city">Hà Tĩnh</td>
                          <td className="address">16 Xô Viết, Nguyễn Du, TP. Hà Tĩnh, Hà Tĩnh</td>
                          <td className="city"><a href="tel:0326547777">0326547777</a></td>
                        </tr>
                        <tr>
                          <td className="no">4</td>
                          <td className="city">Quảng Bình</td>
                          <td className="address">29 Trần Quang Khải, Đồng Phú, TP Đồng Hới, Quảng Bình</td>
                          <td className="city"><a href="tel:02326 55 8888">02326 55 8888</a></td>
                        </tr>
                        <tr>
                          <td className="no">5</td>
                          <td className="city">Quảng Trị</td>
                          <td className="address">01 Hoàng Diệu, Đông Giang, TP Đông Hà, Quảng Trị</td>
                          <td className="city"><a href="tel:0983661252">0983661252</a></td>
                        </tr>
                        <tr>
                          <td className="no">6</td>
                          <td className="city">Thừa Thiên Huế</td>
                          <td className="address">11 Lý Thường Kiệt, Phú Nhuận, TP Huế, Thừa Thiên Huế</td>
                          <td className="city"><a href="tel:0326 527 777">0326 527 777</a></td>
                        </tr>
                        <tr>
                          <th rowSpan={8} className="area">Nam Trung Bộ</th>
                          <td className="no">7</td>
                          <td className="city">Đà Nẵng</td>
                          <td className="address">Lô A2-9 Thăng Long, Hòa Thọ Đông, Cẩm Lệ, Thành phố Đà Nẵng</td>
                          <td className="city"><a href="tel:0326507777">0326 507 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">8</td>
                          <td className="city">Quảng Nam</td>
                          <td className="address">121 Hùng Vương, Tam Kỳ, Quảng Nam</td>
                          <td className="city"><a href="tel:0865 000 357">0865 000 357</a></td>
                        </tr>
                        <tr>
                          <td className="no">9</td>
                          <td className="city">Quảng Ngãi</td>
                          <td className="address">Số 07B Nguyễn Chánh, Trần Phú, TP Quảng Ngãi, Quảng Ngãi</td>
                          <td className="city"><a href="tel:03626497777">0362 649 7777</a></td>
                        </tr>
                        <tr>
                          <td className="no">10</td>
                          <td className="city">Bình Định</td>
                          <td className="address">01 Đinh Bộ Lĩnh, TP Quy Nhơn, Bình Định</td>
                          <td className="city"><a href="tel:0326987777">0326 987 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">11</td>
                          <td className="city">Phú Yên</td>
                          <td className="address">Hùng Vương, Phường 9, TP Tuy Hòa, Phú Yên</td>
                          <td className="city"><a href="tel:0326967777">0326 967 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">12</td>
                          <td className="city">Khánh Hoà</td>
                          <td className="address">9 Võ Thị Sáu, TP Nha Trang, Khánh Hòa</td>
                          <td className="city"><a href="tel:02586250000">0258 625 0000</a></td>
                        </tr>
                        <tr>
                          <td className="no">13</td>
                          <td className="city">Ninh Thuận</td>
                          <td className="address">369 Đường 21/8, Phước Mỹ, TP. Phan Rang Tháp Chàm, Ninh Thuận</td>
                          <td className="city"><a href="tel:0326897777">0326 897 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">14</td>
                          <td className="city">Bình Thuận</td>
                          <td className="address">Phường Phú Thủy, Thành phố Phan Thiết, Bình Thuận</td>
                          <td className="city"><a href="tel:0328 417 777">0328 417 777</a></td>
                        </tr>

                        <tr>
                          <th rowSpan={5} className="area">Tây Nguyên</th>
                          <td className="no">15</td>
                          <td className="city">Kon Tum</td>
                          <td className="address">1075 Phan Đình Phùng, TP Kon Tum, Kon Tum</td>
                          <td className="city"><a href="tel:0376271684">0376 271 684</a></td>
                        </tr>
                        <tr>
                          <td className="no">16</td>
                          <td className="city">Gia Lai</td>
                          <td className="address">87 - 89 Nguyễn Tất Thành, TP Pleiku, Gia Lai</td>
                          <td className="city"><a href="tel:0326 927 777">0326 927 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">17</td>
                          <td className="city">Đắk Lắk</td>
                          <td className="address">48 Lý Tự Trọng, TP Buôn Ma Thuột, Đắk Lắk</td>
                          <td className="city"><a href="tel:0326917777">0326 917 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">18</td>
                          <td className="city">Đắk Nông</td>
                          <td className="address">308 Tôn Đức Thắng, p.Nghia Thành, Gia Nghĩa, Đắc Nông</td>
                          <td className="city"><a href="tel:0326017777">0326 017 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">19</td>
                          <td className="city">Lâm Đồng</td>
                          <td className="address">39 Hùng Vương, P9, TP Đà Lạt, Lâm Đồng</td>
                          <td className="city"><a href="tel:0326937777">0326 937 777</a></td>
                        </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div className="item-warranty">
                    <span className="bg_top">Miền Nam</span>
                    <div className="table-responsive">
                      <table className="table align-middle table-striped table-hover">
                        <thead>
                        <tr>
                          <th scope="col" className="area">Khu vực</th>
                          <th scope="col" className="no">STT</th>
                          <th scope="col" className="city">Tỉnh/Thành phố</th>
                          <th scope="col" className="address">Địa chỉ</th>
                          <th scope="col" className="phone">Số điện thoại</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                          <th rowSpan={6} className="area">Đông Nam Bộ</th>
                          <td className="no">1</td>
                          <td className="city">Hồ Chí Minh</td>
                          <td className="address">H158 Hoàng Hoa Thám, Tân Bình, TP Hồ Chí Minh</td>
                          <td className="phone"><a href="tel:028 22333332">0282 2333 332</a></td>
                        </tr>
                        <tr>
                          <td className="no">2</td>
                          <td className="city">Bà Rịa - Vũng Tàu</td>
                          <td className="address">32K2 đường Trịnh Hoài Đức, P7, TP Vũng Tàu, Bà Rịa - Vũng Tàu</td>
                          <td className="phone"><a href="tel:0963538777">096 353 8777</a></td>
                        </tr>
                        <tr>
                          <td className="no">3</td>
                          <td className="city">Bình Dương</td>
                          <td className="address">Số 277 Đại Lộ Bình Dương, P.Chánh Nghĩa, Tp Thủ Dầu Một, Bình Dương
                          </td>
                          <td className="city"><a href="tel:0989400061">0989 400 061</a></td>
                        </tr>
                        <tr>
                          <td className="no">4</td>
                          <td className="city">Bình Phước</td>
                          <td className="address">818 Phú Riềng Đỏ, P. Tân Xuân, TX. Đồng Xoài, Bình Phước</td>
                          <td className="city"><a href="tel:0326027777">0326 027 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">5</td>
                          <td className="city">Đồng Nai</td>
                          <td className="address">2047 Đ.Nguyễn Ái Quốc, Trung Dũng, Biên Hòa, Đồng Nai</td>
                          <td className="city"><a href="tel:0327057777">0327 057 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">6</td>
                          <td className="city">Tây Ninh</td>
                          <td className="address">162 Đường 30-4, P3, TP Tây Ninh, Tây Ninh</td>
                          <td className="city"><a href="tel:0989400060">0989 400 060</a></td>
                        </tr>
                        <tr>
                          <th rowSpan={13} className="area">Đồng bằng sông Cửu Long</th>
                          <td className="no">7</td>
                          <td className="city">An Giang</td>
                          <td className="address">Số 188A10 Hàm Nghi, Bình Khánh, TP Long Xuyên, An Giang</td>
                          <td className="city"><a href="tel:0962922345">096 292 2345</a></td>
                        </tr>
                        <tr>
                          <td className="no">8</td>
                          <td className="city">Bạc Liêu</td>
                          <td className="address">02 Quốc lộ 1A, P7, TP Bạc Liêu, Bạc Liêu</td>
                          <td className="city"><a href="tel:0988888770">098 888 8770</a></td>
                        </tr>
                        <tr>
                          <td className="no">9</td>
                          <td className="city">Bến Tre</td>
                          <td className="address">68C Nguyễn Văn Tư, P7, TP Bến Tre, Bến Tre</td>
                          <td className="city"><a href="tel:0327 197 777">0327 197 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">10</td>
                          <td className="city">Cà Mau</td>
                          <td className="address">298 Trần Hưng Đạo, P5, TP Cà Mau, Cà Mau</td>
                          <td className="city"><a href="tel:0979277292">0979 277 292</a></td>
                        </tr>
                        <tr>
                          <td className="no">11</td>
                          <td className="city">Cần Thơ</td>
                          <td className="address">210 Trần Phú, Cái Khế, Ninh Kiều, Cần Thơ</td>
                          <td className="city"><a href="tel:032710777">032710777</a></td>
                        </tr>
                        <tr>
                          <td className="no">12</td>
                          <td className="city">Đồng Tháp</td>
                          <td className="address">267, Ngô Thời Nhậm, Phường 1, Tp Cao Lãnh, Đồng Tháp</td>
                          <td className="city"><a href="tel:0327057777">0327 057 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">13</td>
                          <td className="city">Hậu Giang</td>
                          <td className="address">65 Võ Văn Kiệt, P5, TP Vị Thanh, Hậu Giang</td>
                          <td className="city"><a href="tel:0327147777">0327 147 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">14</td>
                          <td className="city">Kiên Giang</td>
                          <td className="address">654 Nguyễn Trung Trực, Vĩnh Lạc, TP Rạch Giá, Kiên Giang</td>
                          <td className="city"><a href="tel:0327167777">0327 167 777</a></td>
                        </tr>

                        <tr>
                          <td className="no">15</td>
                          <td className="city">Long An</td>
                          <td className="address">20 Quốc lộ 1, Khu phố Bình Phú, Phường 5, Tp Tân An, Long An</td>
                          <td className="city"><a href="tel:0976127117">0976 127 117</a></td>
                        </tr>
                        <tr>
                          <td className="no">16</td>
                          <td className="city">Sóc Trăng</td>
                          <td className="address">84 Lê Duẫn, P3, TP Sóc Trăng, Sóc Trăng</td>
                          <td className="city"><a href="tel:032 713 7777">032 713 7777</a></td>
                        </tr>
                        <tr>
                          <td className="no">17</td>
                          <td className="city">Tiền Giang</td>
                          <td className="address">66 Đinh Bộ Lĩnh, KP5, P9, TP Mỹ Tho, Tiền Giang</td>
                          <td className="city"><a href="tel:0327207777">0327 207 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">18</td>
                          <td className="city">Trà Vinh</td>
                          <td className="address">156 Nguyễn Đáng, P7, TP. Trà Vinh, Trà Vinh</td>
                          <td className="city"><a href="tel:00327097777">0327 097 777</a></td>
                        </tr>
                        <tr>
                          <td className="no">19</td>
                          <td className="city">Vĩnh Long</td>
                          <td className="address">1C Trưng Nữ Vương, P1, TP Vĩnh Long, Vĩnh Long</td>
                          <td className="city"><a href="tel:0327087777">0327 087 777</a></td>
                        </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>}
              </main>

            </div>
          </section>
          <section className="block-session" id="block-app">
            <div className="container">
              <div className="header-block">
                <h3 className="title-h3">Cài đặt App Life Care</h3>
                <p className="subtitle">Life Care - “Dựng xây cuộc sống mới”</p>
              </div>
              <div className="d-flex justify-content-between">
                <div className="content">
                  <div className="wrap-qrcode">
                    <div className="images">
                      <img src="/current_web/ch_play.png" alt=""/>
                      <span>CH Play</span>
                    </div>
                    <div className="images">
                      <img src="/current_web/app_store.png" alt=""/>
                      <span>App Store</span>
                    </div>
                  </div>
                  <div className="content-inner">
                    <h6>Hướng dẫn cài đặt app Life Care</h6>
                    <ul>
                      <li>
                        <strong>Bước 1: </strong>Quét mã QR ở trên tương ứng kho ứng dụng trên hệ điều hành điện thoại
                        của bạn.
                      </li>
                      <li>
                        <strong>Bước 2: </strong>Cài đặt app và thực hiện đăng ký tài khoản.
                      </li>
                      <li>
                        <strong>Bước 3: </strong>Lướt Life Care để tra cứu thông tin và mua sắm ngay thôi!!!
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="images">
                  <img src="/current_web/iphone.png" alt=""/>
                </div>
              </div>
            </div>
          </section>
          <section className="block-session" id="block-supports">
            <div className="container">
              <div className="header-block">
                <h3 className="title-h3">Hỗ trợ</h3>
              </div>
              <ul className="list-support">
                <li>
                  <span className="icon"><img src="/current_web/icon1.png" alt=""/></span>
                  <span>Hỗ trợ và xác nhận đơn hàng trong 24h</span>
                </li>
                <li>
                  <span className="icon"><img src="/current_web/icon4.png" alt=""/></span>
                  <span>Hotline CSKH: 1900989868 </span>
                </li>
                <li>
                  <span className="icon"><img src="/current_web/icon2.png" alt=""/></span>
                  <span>Thanh toán linh hoạt khi nhận hàng</span>
                </li>
                <li>
                  <span className="icon"><img src="/current_web/icon5.png" alt=""/></span>
                  <span>Email: cskhcongtrinhviettel@viettel.com.vn</span>
                </li>
                <li>
                  <span className="icon"><img src="/current_web/icon6.png" alt=""/></span>
                  <span>Thời gian tiếp nhận: 8:00-17:30</span>
                </li>
              </ul>
            </div>
          </section>
        </main>
        <footer className="footer">
          <div className="container">
            <div className="d-flex align-items-center">
              <div className="logo-footer">
                <a href="https://baohanh.viettelaio.vn/#"><img src="/current_web/logo_footer.png" alt=""/></a>
              </div>
              <div className="infomation">
                <p className="address">
                  <strong>Địa chỉ: </strong>
                  <span>Số 6 Phạm Văn Bạch, Phường Yên Hòa, Quận Cầu Giấy, TP Hà Nội</span>
                </p>
                <div className="wrap-phone d-flex align-items-center">
                  <p className="phone">
                    <strong>Điện thoại:</strong>
                    <span><a href="tel:02462661225">024.6266.1225</a></span>
                  </p>
                  <p className="email">
                    <strong>E-mail: </strong>
                    <span><a href="mailto:congtrinhviettel@viettel.com.vn">congtrinhviettel@viettel.com.vn</a></span>
                  </p>
                </div>
                <p className="website">
                  <strong>Website: </strong>
                  <span><a href="https://baohanh.viettelaio.vn/www.congtrinhviettel.com.vn"
                           target="_blank">www.congtrinhviettel.com.vn</a> / <a
                    href="https://baohanh.viettelaio.vn/www.viettelcontruction.com.vn"
                    target="_blank">www.viettelcontruction.com.vn</a></span>
                </p>
              </div>
            </div>
          </div>
        </footer>
      </div>
      <div className="overlay"></div>
      <div className="contact" id="info-contact">
        <a className="phone-contact" href="tel:1900989868">
          <i className="fa fa-phone"></i>
        </a>
        <a className="mail-contact" href="mailto:cskhcongtrinhviettel@viettel.com.vn">
          <i className="fa fa-envelope"></i>
        </a>
      </div>
      <Script src="/current_web/jquery-3.5.1.min.js.download"></Script>
      <Script src="/current_web/owl.carousel.min.js.download"></Script>
      <Script src="/current_web/bootstrap.min.js.download"></Script>
      <Script src="/current_web/main.js.download"></Script>
      </body>
    </>
  )
}
